GROUPS = {
    "Common": [
        "common",
    ],
    "MCP": [
        "mcp",
        "fastmcp",
    ],
    "Agents": [
        "openai_agents",
        "pydantic_ai",
    ],
    "AI Workflow": [
        "langchain-base",
        "langchain-notiktoken",
        "langgraph",
    ],
    "AI": [
        "anthropic",
        "cohere",
        "google_genai",
        "huggingface_hub",
        "litellm",
        "openai-base",
        "openai-notiktoken",
    ],
    "Cloud": [
        "aws_lambda",
        "boto3",
        "chalice",
        "cloud_resource_context",
        "gcp",
    ],
    "DBs": [
        "asyncpg",
        "clickhouse_driver",
        "pymongo",
        "redis",
        "redis_py_cluster_legacy",
        "sqlalchemy",
    ],
    "Flags": [
        "launchdarkly",
        "openfeature",
        "statsig",
        "unleash",
    ],
    "Gevent": [
        "gevent",
    ],
    "GraphQL": [
        "ariadne",
        "gql",
        "graphene",
        "strawberry",
    ],
    "Network": [
        "grpc",
        "httpx",
        "httpx2",
        "pyreqwest",
        "requests",
    ],
    "Tasks": [
        "arq",
        "beam",
        "celery",
        "dramatiq",
        "huey",
        "ray",
        "rq",
        "spark",
    ],
    "Web 1": [
        "django",
        "flask",
        "starlette",
        "fastapi",
    ],
    "Web 2": [
        "aiohttp",
        "asgi",
        "bottle",
        "falcon",
        "litestar",
        "pyramid",
        "quart",
        "sanic",
        "starlite",
        "tornado",
    ],
    "Misc": [
        "loguru",
        "opentelemetry",
        "otlp",
        "potel",
        "pure_eval",
        "trytond",
        "typer",
        "integration_deactivation",
        "shadowed_module",
    ],
}
